`default_nettype none

// The open build flow defines OMCU_ROM_IMAGE_BUILD and supplies this generated
// include before Yosys parses both this wrapper and the system containing
// `$readmemh`. Changing a string parameter later with `chparam` is too late
// for a reliable synthesized memory image. Normal RTL simulation and the
// vendor project do not define the macro and retain the checked-in fixture.
`ifdef OMCU_ROM_IMAGE_BUILD
`include "omcu_rom_image_config.vh"
`endif

// Tang Nano 9K production MCU target.  It runs the portable SoC directly from
// the board's 27 MHz oscillator, avoiding an unvalidated PLL configuration.
//
// The default memory geometry is deliberately the largest all-BSRAM layout
// which this project supports on GW1NR-9C: 8 KiB ROM plus 44 KiB SRAM.  The
// open P&R release flow checks the resulting 26/26 BSRAM use.  Keep this top
// parameterized so an application can trade memory for LUT/DSP experiments,
// but do not change the linker script unless the firmware image is rebuilt.
module omcu_tn9k_bringup_top #(
`ifdef OMCU_ROM_IMAGE_BUILD
  parameter ROM_INIT_FILE = `OMCU_ROM_IMAGE_FILE,
`else
  parameter ROM_INIT_FILE = "rtl/platform/tangnano9k/firmware/gpio_bringup.hex",
`endif
  parameter integer ROM_WORDS = 2048,
  parameter integer SRAM_BYTES = 45056,
  parameter integer USER_FLASH_BYTES = 4,
  parameter integer USER_FLASH_PRESENT = 0,
  parameter integer USER_FLASH_USE_GOWIN_PRIMITIVE = 0,
  parameter integer APPLICATION_BOOT_MODE = 0
) (
  input  logic       clk_27m_i,
  input  logic       resetn_i,
  input  logic       uart_rx_i,
  output logic       uart_tx_o,
  output logic [5:0] led_n_o,

  // J5/TF-card signal group. SPI0 owns these pins while the MCU image runs;
  // do not insert or access a microSD card at the same time.
  input  logic       spi0_miso_i,
  output logic       spi0_mosi_o,
  output logic       spi0_sck_o,
  output logic       spi0_cs_n_o,

  // Open-drain I2C0, plus three GPIOs on the 3.3 V expansion group.
  // External I2C pull-ups are mandatory for a real bus.
  inout  wire        i2c0_scl_io,
  inout  wire        i2c0_sda_io,
  output logic       pwm0_o,
  inout  wire [2:0]  gpio_io
);

  logic [2:0] reset_release_q;
  logic       sys_rst_ni;
  logic [8:0] gpio_in;
  logic [8:0] gpio_out;
  logic [8:0] gpio_oe;
  logic       i2c_scl_i;
  logic       i2c_sda_i;
  logic       i2c_scl_drive_low;
  logic       i2c_sda_drive_low;
  logic       cpu_trap;
  logic       bus_error;
  logic       watchdog_reset_request;

  // Assert asynchronously; deassert after three clean 27 MHz clock edges.
  // The watchdog request is generated by synchronous MCU logic, so it is a
  // synchronous reset-sequencer input rather than a second asynchronous reset
  // event. That maps cleanly to Gowin flip-flops and still restarts the SoC.
  always_ff @(posedge clk_27m_i or negedge resetn_i) begin
    if (!resetn_i) begin
      reset_release_q <= 3'b000;
    end else if (watchdog_reset_request) begin
      reset_release_q <= 3'b000;
    end else begin
      reset_release_q <= {reset_release_q[1:0], 1'b1};
    end
  end

  assign sys_rst_ni = reset_release_q[2];

  omcu_picorv32_system #(
    .GPIO_COUNT(9),
    .ROM_WORDS(ROM_WORDS),
    .SRAM_BYTES(SRAM_BYTES),
    .USER_FLASH_BYTES(USER_FLASH_BYTES),
    .USER_FLASH_PRESENT(USER_FLASH_PRESENT),
    .USER_FLASH_USE_GOWIN_PRIMITIVE(USER_FLASH_USE_GOWIN_PRIMITIVE),
    .APPLICATION_BOOT_MODE(APPLICATION_BOOT_MODE),
    .ROM_INIT_FILE(ROM_INIT_FILE)
  ) system (
    .clk_i(clk_27m_i),
    .rst_ni(sys_rst_ni),
    .gpio_in_i(gpio_in),
    .gpio_out_o(gpio_out),
    .gpio_oe_o(gpio_oe),
    .gpio_irq_o(),
    .uart_rx_i(uart_rx_i),
    .uart_tx_o(uart_tx_o),
    .uart_irq_o(),
    .timer_irq_o(),
    .spi_miso_i(spi0_miso_i),
    .spi_mosi_o(spi0_mosi_o),
    .spi_sck_o(spi0_sck_o),
    .spi_cs_n_o(spi0_cs_n_o),
    .spi_irq_o(),
    .i2c_scl_i(i2c_scl_i),
    .i2c_sda_i(i2c_sda_i),
    .i2c_scl_drive_low_o(i2c_scl_drive_low),
    .i2c_sda_drive_low_o(i2c_sda_drive_low),
    .i2c_irq_o(),
    .wdt_irq_o(),
    .wdt_reset_req_o(watchdog_reset_request),
    .pwm_o(pwm0_o),
    .cpu_trap_o(cpu_trap),
    .bus_error_o(bus_error)
  );

  // GPIO[0:5] are the six on-board active-low LEDs. GPIO[6:8] are brought to
  // the expansion pins. GPIO output-enable is honoured: applications can
  // safely use the three expansion pins as inputs without a permanently
  // driven FPGA output.
  assign gpio_in[5:0] = 6'b000000;
  assign gpio_in[8:6] = gpio_io;
  assign gpio_io[0] = gpio_oe[6] ? gpio_out[6] : 1'bz;
  assign gpio_io[1] = gpio_oe[7] ? gpio_out[7] : 1'bz;
  assign gpio_io[2] = gpio_oe[8] ? gpio_out[8] : 1'bz;

  // I2C is wired as true open-drain at the pad boundary.  Never drive a one:
  // releasing the line lets the external pull-up and other bus targets decide
  // its level, which preserves the peripheral's arbitration/error checks.
  assign i2c0_scl_io = i2c_scl_drive_low ? 1'b0 : 1'bz;
  assign i2c0_sda_io = i2c_sda_drive_low ? 1'b0 : 1'bz;
  assign i2c_scl_i = i2c0_scl_io;
  assign i2c_sda_i = i2c0_sda_io;

  genvar led_index;
  generate
    for (led_index = 0; led_index < 6; led_index = led_index + 1) begin : led_map
      // A disabled GPIO leaves the corresponding on-board LED off.
      assign led_n_o[led_index] = gpio_oe[led_index] ? ~gpio_out[led_index] : 1'b1;
    end
  endgenerate

endmodule

`default_nettype wire
