`default_nettype none

// The open build flow defines OMCU_ROM_IMAGE_BUILD and supplies this generated
// include before Yosys parses both this wrapper and the system containing
// `$readmemh`. Changing a string parameter later with `chparam` is too late
// for a reliable synthesized memory image. Normal RTL simulation and the
// vendor project do not define the macro and retain the checked-in fixture.
`ifdef OMCU_ROM_IMAGE_BUILD
`include "omcu_rom_image_config.vh"
`endif

// Tang Nano 9K production MCU target.  It runs the portable SoC directly from
// the board's 27 MHz oscillator, avoiding an unvalidated PLL configuration.
//
// The default memory geometry is deliberately the largest all-BSRAM layout
// which this project supports on GW1NR-9C: 8 KiB ROM plus 44 KiB SRAM.  The
// open P&R release flow checks the resulting 26/26 BSRAM use.  Keep this top
// parameterized so an application can trade memory for LUT/DSP experiments,
// but do not change the linker script unless the firmware image is rebuilt.
module omcu_tn9k_bringup_top #(
`ifdef OMCU_ROM_IMAGE_BUILD
  parameter ROM_INIT_FILE = `OMCU_ROM_IMAGE_FILE,
`else
  parameter ROM_INIT_FILE = "rtl/platform/tangnano9k/firmware/gpio_bringup.hex",
`endif
  parameter integer ROM_WORDS = 2048,
  parameter integer SRAM_BYTES = 45056,
  parameter integer USER_FLASH_BYTES = 4,
  parameter integer USER_FLASH_PRESENT = 0,
  parameter integer USER_FLASH_USE_GOWIN_PRIMITIVE = 0,
  parameter integer APPLICATION_BOOT_MODE = 0
) (
  input  logic       clk_27m_i,
  input  logic       resetn_i,
  input  logic       uart_rx_i,
  output logic       uart_tx_o,
  output logic [5:0] led_n_o,

  // J5/TF-card signal group. SPI0 owns these pins while the MCU image runs;
  // do not insert or access a microSD card at the same time.
  input  logic       spi0_miso_i,
  output logic       spi0_mosi_o,
  output logic       spi0_sck_o,
  output logic       spi0_cs_n_o,

  // Open-drain I2C0, plus twelve GPIO-capable pads on the 3.3 V J5 group.
  // gpio_io[0:2] are the original plain GPIOs; gpio_io[3:11] are connected
  // to RGB-LCD-shared header lines and require the documented pinmux/HIL
  // checks before a board-level product may use them. External I2C pull-ups
  // are mandatory for a real bus.
  inout  wire        i2c0_scl_io,
  inout  wire        i2c0_sda_io,
  output logic       pwm0_o,
  inout  wire [11:0] gpio_io
);

  localparam logic [31:0] RESET_CAUSE_EXTERNAL = 32'h0000_0001;
  localparam logic [31:0] RESET_CAUSE_WATCHDOG = 32'h0000_0002;
  localparam logic [31:0] RESET_CAUSE_SOFTWARE = 32'h0000_0004;

  logic [2:0] reset_release_q;
  logic       sys_rst_ni;
  logic [31:0] reset_cause_q;
  logic [31:0] reset_count_q;
  logic        boot_request_pending_q;
  logic        software_boot_request;
  logic        boot_request_ack;
  logic [17:0] gpio_in;
  logic [17:0] gpio_out;
  logic [17:0] gpio_oe;
  logic       i2c_scl_i;
  logic       i2c_sda_i;
  logic       i2c_scl_drive_low;
  logic       i2c_sda_drive_low;
  logic       cpu_trap;
  logic       bus_error;
  logic       watchdog_reset_request;
  logic       uart1_tx;
  logic [3:0] pwm1;
  logic       pinmux_uart1_enable;
  logic       pinmux_pwm1_enable;
  logic       pinmux_timer1_enable;
  logic       pinmux_pulse0_enable;
  logic [11:0] gpio_pad_out;
  logic [11:0] gpio_pad_oe;

  // Assert asynchronously; deassert after three clean 27 MHz clock edges.
  // Watchdog and software-bootloader requests are generated by synchronous
  // MCU logic, so they enter this single reset sequencer rather than becoming
  // competing asynchronous resets.  Cause/count and the bootloader-request
  // latch intentionally remain in this outer clock domain while the SoC is
  // reset, allowing the next Boot ROM instance to inspect and consume them.
  always_ff @(posedge clk_27m_i or negedge resetn_i) begin
    if (!resetn_i) begin
      reset_release_q <= 3'b000;
      reset_cause_q <= RESET_CAUSE_EXTERNAL;
      reset_count_q <= 32'h0000_0000;
      boot_request_pending_q <= 1'b0;
    end else begin
      if (boot_request_ack) begin
        boot_request_pending_q <= 1'b0;
      end

      if (software_boot_request) begin
        reset_release_q <= 3'b000;
        reset_cause_q <= RESET_CAUSE_SOFTWARE;
        reset_count_q <= reset_count_q + 32'd1;
        boot_request_pending_q <= 1'b1;
      end else if (watchdog_reset_request) begin
        reset_release_q <= 3'b000;
        reset_cause_q <= RESET_CAUSE_WATCHDOG;
        reset_count_q <= reset_count_q + 32'd1;
      end else begin
        reset_release_q <= {reset_release_q[1:0], 1'b1};
      end
    end
  end

  assign sys_rst_ni = reset_release_q[2];

  omcu_picorv32_system #(
    .GPIO_COUNT(18),
    .GPIO_EXPANSION_PRESENT(1),
    .UART1_PRESENT(1),
    .PWM1_PRESENT(1),
    .TIMER1_PRESENT(1),
    .ALARM0_PRESENT(1),
    .PULSE0_PRESENT(1),
    .PINMUX_PRESENT(1),
    .DIAGNOSTICS_PRESENT(1),
    .ROM_WORDS(ROM_WORDS),
    .SRAM_BYTES(SRAM_BYTES),
    .USER_FLASH_BYTES(USER_FLASH_BYTES),
    .USER_FLASH_PRESENT(USER_FLASH_PRESENT),
    .USER_FLASH_USE_GOWIN_PRIMITIVE(USER_FLASH_USE_GOWIN_PRIMITIVE),
    .APPLICATION_BOOT_MODE(APPLICATION_BOOT_MODE),
    .ROM_INIT_FILE(ROM_INIT_FILE)
  ) system (
    .clk_i(clk_27m_i),
    .rst_ni(sys_rst_ni),
    .reset_cause_i(reset_cause_q),
    .reset_count_i(reset_count_q),
    .boot_request_pending_i(boot_request_pending_q),
    .software_boot_request_o(software_boot_request),
    .boot_request_ack_o(boot_request_ack),
    .gpio_in_i(gpio_in),
    .gpio_out_o(gpio_out),
    .gpio_oe_o(gpio_oe),
    .gpio_irq_o(),
    .uart_rx_i(uart_rx_i),
    .uart_tx_o(uart_tx_o),
    .uart_irq_o(),
    .uart1_rx_i(gpio_io[11]),
    .uart1_tx_o(uart1_tx),
    .uart1_irq_o(),
    .timer_irq_o(),
    .timer1_capture_a_i(gpio_io[8]),
    .timer1_capture_b_i(gpio_io[9]),
    .timer1_irq_o(),
    .pulse0_i(gpio_io[2:0]),
    .alarm_irq_o(),
    .pulse0_irq_o(),
    .spi_miso_i(spi0_miso_i),
    .spi_mosi_o(spi0_mosi_o),
    .spi_sck_o(spi0_sck_o),
    .spi_cs_n_o(spi0_cs_n_o),
    .spi_irq_o(),
    .i2c_scl_i(i2c_scl_i),
    .i2c_sda_i(i2c_sda_i),
    .i2c_scl_drive_low_o(i2c_scl_drive_low),
    .i2c_sda_drive_low_o(i2c_sda_drive_low),
    .i2c_irq_o(),
    .wdt_irq_o(),
    .wdt_reset_req_o(watchdog_reset_request),
    .pwm_o(pwm0_o),
    .pwm1_o(pwm1),
    .pinmux_uart1_enable_o(pinmux_uart1_enable),
    .pinmux_pwm1_enable_o(pinmux_pwm1_enable),
    .pinmux_timer1_enable_o(pinmux_timer1_enable),
    .pinmux_pulse0_enable_o(pinmux_pulse0_enable),
    .cpu_trap_o(cpu_trap),
    .bus_error_o(bus_error)
  );

  // GPIO[0:5] are the six on-board active-low LEDs. GPIO[6:17] are brought
  // to the 12-pad J5 expansion profile. GPIO output-enable is honoured: an
  // application can safely use every expansion pin as an input without a
  // permanently driven FPGA output.
  assign gpio_in[5:0] = 6'b000000;
  assign gpio_in[17:6] = gpio_io;

  always_comb begin
    gpio_pad_out = gpio_out[17:6];
    gpio_pad_oe = gpio_oe[17:6];
    if (pinmux_uart1_enable) begin
      // UART1 claims GPIO10 (J5.18 / pad 53) for TX and GPIO11
      // (J5.19 / pad 54) for RX.  RX is always released at the pad boundary.
      gpio_pad_out[10] = uart1_tx;
      gpio_pad_oe[10] = 1'b1;
      gpio_pad_oe[11] = 1'b0;
    end
    if (pinmux_pwm1_enable) begin
      // PWM1 channels 0..3 use GPIO4..7 / J5.12..15.  They intentionally
      // share one timer phase and are all driven low by the peripheral while
      // disabled, which is safer than silently retaining a former GPIO state.
      gpio_pad_out[4] = pwm1[0];
      gpio_pad_out[5] = pwm1[1];
      gpio_pad_out[6] = pwm1[2];
      gpio_pad_out[7] = pwm1[3];
      gpio_pad_oe[4] = 1'b1;
      gpio_pad_oe[5] = 1'b1;
      gpio_pad_oe[6] = 1'b1;
      gpio_pad_oe[7] = 1'b1;
    end
    if (pinmux_timer1_enable) begin
      // TIMER1 capture/encoder pins A/B use GPIO8/9 / J5.16/17.  The
      // alternate function is input-only, so it always releases the FPGA
      // drivers before an external encoder or industrial input can drive it.
      gpio_pad_oe[8] = 1'b0;
      gpio_pad_oe[9] = 1'b0;
    end
    if (pinmux_pulse0_enable) begin
      // PULSE0 channel 0..2 owns GPIO0..2 / J5.8..10 as input-only paths.
      // Releasing every FPGA driver is mandatory before an external Hall,
      // flow or pulse sensor can safely drive the reviewed pad.
      gpio_pad_oe[0] = 1'b0;
      gpio_pad_oe[1] = 1'b0;
      gpio_pad_oe[2] = 1'b0;
    end
  end

  genvar gpio_index;
  generate
    for (gpio_index = 0; gpio_index < 12; gpio_index = gpio_index + 1) begin : gpio_pad_map
      assign gpio_io[gpio_index] = gpio_pad_oe[gpio_index] ?
                                   gpio_pad_out[gpio_index] : 1'bz;
    end
  endgenerate

  // I2C is wired as true open-drain at the pad boundary.  Never drive a one:
  // releasing the line lets the external pull-up and other bus targets decide
  // its level, which preserves the peripheral's arbitration/error checks.
  assign i2c0_scl_io = i2c_scl_drive_low ? 1'b0 : 1'bz;
  assign i2c0_sda_io = i2c_sda_drive_low ? 1'b0 : 1'bz;
  assign i2c_scl_i = i2c0_scl_io;
  assign i2c_sda_i = i2c0_sda_io;

  genvar led_index;
  generate
    for (led_index = 0; led_index < 6; led_index = led_index + 1) begin : led_map
      // A disabled GPIO leaves the corresponding on-board LED off.
      assign led_n_o[led_index] = gpio_oe[led_index] ? ~gpio_out[led_index] : 1'b1;
    end
  endgenerate

endmodule

`default_nettype wire
